# Generated by Django 6.0.3 on 2026-03-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('answer', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for this label')),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': 'Q&As',
                'ordering': ['label'],
            },
        ),
    ]
