# Generated by Django 4.2.29 on 2026-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='question',
            field=models.CharField(default='New Medical Question', help_text='A natural language question (e.g. What is insulin?)', max_length=255),
        ),
        migrations.AlterField(
            model_name='qna',
            name='label',
            field=models.CharField(help_text='A unique identifier for this topic (e.g. diabetes_basics)', max_length=100, unique=True),
        ),
    ]
